include: package:flutter_lints/flutter.yaml

linter:
  rules:
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
    avoid_function_literals_in_foreach_calls: false
    curly_braces_in_flow_control_structures: false
    non_constant_identifier_names: false
    invalid_annotation_target: false
